apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pa-study-hub-flashcard-service
  annotations:
    run.googleapis.com/ingress: internal-and-cloud-load-balancing
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "8"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/cloudsql-instances: "PROJECT_ID:REGION:pa-study-hub-postgres"
    spec:
      serviceAccountName: pa-study-hub-sa@PROJECT_ID.iam.gserviceaccount.com
      containers:
        - image: REGION-docker.pkg.dev/PROJECT_ID/pa-study-hub/flashcard-service:latest
          ports:
            - containerPort: 8081
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: DB_PORT
              value: "5432"
            - name: DB_HOST
              value: /cloudsql/PROJECT_ID:REGION:pa-study-hub-postgres
            - name: PROGRESS_SERVICE_URL
              value: https://pa-study-hub-progress-service-HASH-uc.a.run.app
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: flashcard-service-db-name
                  key: latest
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: flashcard-service-db-username
                  key: latest
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flashcard-service-db-password
                  key: latest
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: latest
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            periodSeconds: 30
